source('SplitDB.R')
load('mm9.RData')
SplitDB(refseq, 'mm9', 'refseq')
SplitDB(ensembl, 'mm9', 'ensembl')
load('hg19.RData')
SplitDB(refseq, 'hg19', 'refseq')
SplitDB(ensembl, 'hg19', 'ensembl')
load('rn4.RData')
SplitDB(refseq, 'rn4', 'refseq')
SplitDB(ensembl, 'rn4', 'ensembl')
load('sacCer3.RData')
SplitDB(ensembl, 'sacCer3', 'ensembl')
